DROP TABLE IF EXISTS productos;

CREATE TABLE productos (
  id_Producto INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  descripcion VARCHAR(100),
  cantidad INT,
  precio DOUBLE,
  anio_Fabrica INT
);

INSERT INTO productos (descripcion, cantidad, precio, anio_Fabrica)
VALUES ('Camiseta', 10, 19.99, 2022);

INSERT INTO productos (descripcion, cantidad, precio, anio_Fabrica)
VALUES ('Pantalones', 5, 39.99, 2021);

INSERT INTO productos (descripcion, cantidad, precio, anio_Fabrica)
VALUES ('Zapatos', 8, 79.99,2020);

INSERT INTO productos (descripcion, cantidad, precio, anio_Fabrica)
VALUES ('Sombrero', 3, 14.99, 2023);

INSERT INTO productos (descripcion, cantidad, precio, anio_Fabrica)
VALUES ('Bolso', 2, 29.99, 2022);

INSERT INTO productos (descripcion, cantidad, precio, anio_Fabrica)
VALUES ('Gafas de sol', 6, 49.99, 2023);
